In [1]:
import pandas as pd
import numpy as np
import pickle as pk
import matplotlib.pyplot as mlt

In [2]:
df_credit=pd.read_csv("tmdb_5000_credits.csv")
df_credit.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [3]:
df_movie=pd.read_csv("tmdb_5000_movies.csv")
df_movie.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

## Merging both the datasets

In [4]:
df_movie=df_movie.merge(df_credit,on='title')
df_movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1499 entries, 0 to 1498
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                1499 non-null   int64
 1   genres                1499 non-null   object
 2   homepage              701 non-null    object
 3   id                    1499 non-null   int64
 4   keywords              1499 non-null   object
 5   original_language     1499 non-null   object
 6   original_title        1499 non-null   object
 7   overview              1499 non-null   object
 8   popularity            1499 non-null   float64
 9   production_companies  1499 non-null   object
 10  production_countries  1499 non-null   object
 11  release_date          1499 non-null   object
 12  revenue               1499 non-null   int64
 13  runtime               1499 non-null   int64
 14  spoken_languages      1499 non-null   object
 15  status                1499 non-null   object
 16  tagline               1424 non-null   object
 17  title                 1499 non-null   object
 18  vote_average          1499 non-null   float64
 19  vote_count            1499 non-null   int64
 20  movie_id              1499 non-null   int64
 21  cast                  1499 non-null   object
 22  crew                  1499 non-null   object
dtypes: float64(2), int64(6), object(15)
memory usage: 269.5+ KB

## Selecting the required Columns

In [5]:
movie=df_movie[['id','genres','title','overview','keywords','cast','crew']]

 ## finding the missing values in data

In [6]:
movie.isnull().sum()

id          0
genres      0
title       0
overview    0
keywords    0
cast        0
crew        0
dtype: int64

## removing the missing data movies

In [7]:
movie.dropna(inplace=True)

C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\1521465550.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie.dropna(inplace=True)

 ## checking for any duplicate data of movies (2 or more same rows)

In [8]:
movie.duplicated().sum()

0

In [9]:
movie.genres.iloc[0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

## Converting the columns into more refined form (more understandable & omitting the unnecessary things)

In [10]:
import ast # use to convert a string of list to list

## Proper formatting and extracting the required values

In [11]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [12]:
movie['genres']=movie['genres'].apply(convert)
movie

C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\2952659052.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['genres']=movie['genres'].apply(convert)

,id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]",Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
1494,10719,"[Comedy, Family, Fantasy]",Elf,When young Buddy falls into Santa's gift sack ...,"[{""id"": 65, ""name"": ""holiday""}, {""id"": 603, ""n...","[{""cast_id"": 1, ""character"": ""Buddy"", ""credit_...","[{""credit_id"": ""52fe43a89251416c7501905b"", ""de..."
1495,9294,"[Drama, Fantasy, Romance, Science Fiction]",Phenomenon,An ordinary man sees a bright light descend fr...,"[{""id"": 879, ""name"": ""brain tumor""}, {""id"": 50...","[{""cast_id"": 2, ""character"": ""George Malley"", ...","[{""credit_id"": ""52fe44e3c3a36847f80b002f"", ""de..."
1496,11888,"[Adventure, Comedy, Family]",Snow Dogs,When a Miami dentist inherits a team of sled d...,"[{""id"": 2393, ""name"": ""adoption""}, {""id"": 4010...","[{""cast_id"": 39, ""character"": ""Demon (voice)"",...","[{""credit_id"": ""52fe449b9251416c7503aa43"", ""de..."
1497,9647,"[Fantasy, Comedy, Drama]",Scrooged,"In this modern take on Charles Dickens' ""A Chr...","[{""id"": 65, ""name"": ""holiday""}, {""id"": 7271, ""...","[{""cast_id"": 11, ""character"": ""Francis Xavier ...","[{""credit_id"": ""52fe4516c3a36847f80bba59"", ""de..."
1498,9353,"[Comedy, Family]",Nacho Libre,Nacho Libre is loosely based on the story of F...,"[{""id"": 745, ""name"": ""nun""}, {""id"": 6075, ""nam...","[{""cast_id"": 4, ""character"": ""Nacho"", ""credit_...","[{""credit_id"": ""52fe44ecc3a36847f80b2023"", ""de..."

In [13]:
movie['keywords']=movie['keywords'].apply(convert)
movie

C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\2581588516.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['keywords']=movie['keywords'].apply(convert)

,id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]",Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
1494,10719,"[Comedy, Family, Fantasy]",Elf,When young Buddy falls into Santa's gift sack ...,"[holiday, elves, santa claus, looking for bir...","[{""cast_id"": 1, ""character"": ""Buddy"", ""credit_...","[{""credit_id"": ""52fe43a89251416c7501905b"", ""de..."
1495,9294,"[Drama, Fantasy, Romance, Science Fiction]",Phenomenon,An ordinary man sees a bright light descend fr...,"[brain tumor, telekinesis, genius, terminal il...","[{""cast_id"": 2, ""character"": ""George Malley"", ...","[{""credit_id"": ""52fe44e3c3a36847f80b002f"", ""de..."
1496,11888,"[Adventure, Comedy, Family]",Snow Dogs,When a Miami dentist inherits a team of sled d...,"[adoption, log cabin, alaska, sled dogs]","[{""cast_id"": 39, ""character"": ""Demon (voice)"",...","[{""credit_id"": ""52fe449b9251416c7503aa43"", ""de..."
1497,9647,"[Fantasy, Comedy, Drama]",Scrooged,"In this modern take on Charles Dickens' ""A Chr...","[holiday, tv ratings, comedy, scrooge, christm...","[{""cast_id"": 11, ""character"": ""Francis Xavier ...","[{""credit_id"": ""52fe4516c3a36847f80bba59"", ""de..."
1498,9353,"[Comedy, Family]",Nacho Libre,Nacho Libre is loosely based on the story of F...,"[nun, sport, orphanage, ordensbruder, ringer, ...","[{""cast_id"": 4, ""character"": ""Nacho"", ""credit_...","[{""credit_id"": ""52fe44ecc3a36847f80b2023"", ""de..."

## Extracting the top 3 cast values

In [14]:
def convert3(obj):
    l=[]
    cnt=0
    for i in ast.literal_eval(obj):
        if cnt!=3:
            l.append(i['name'])
            cnt+=1
        else:
            break
    return l

In [15]:
movie['cast']=movie['cast'].apply(convert3)
movie

C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\1925413166.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['cast']=movie['cast'].apply(convert3)

,id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]",Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
1494,10719,"[Comedy, Family, Fantasy]",Elf,When young Buddy falls into Santa's gift sack ...,"[holiday, elves, santa claus, looking for bir...","[Will Ferrell, James Caan, Zooey Deschanel]","[{""credit_id"": ""52fe43a89251416c7501905b"", ""de..."
1495,9294,"[Drama, Fantasy, Romance, Science Fiction]",Phenomenon,An ordinary man sees a bright light descend fr...,"[brain tumor, telekinesis, genius, terminal il...","[John Travolta, Kyra Sedgwick, Forest Whitaker]","[{""credit_id"": ""52fe44e3c3a36847f80b002f"", ""de..."
1496,11888,"[Adventure, Comedy, Family]",Snow Dogs,When a Miami dentist inherits a team of sled d...,"[adoption, log cabin, alaska, sled dogs]","[Jim Belushi, Cuba Gooding Jr., James Coburn]","[{""credit_id"": ""52fe449b9251416c7503aa43"", ""de..."
1497,9647,"[Fantasy, Comedy, Drama]",Scrooged,"In this modern take on Charles Dickens' ""A Chr...","[holiday, tv ratings, comedy, scrooge, christm...","[Bill Murray, Karen Allen, John Forsythe]","[{""credit_id"": ""52fe4516c3a36847f80bba59"", ""de..."
1498,9353,"[Comedy, Family]",Nacho Libre,Nacho Libre is loosely based on the story of F...,"[nun, sport, orphanage, ordensbruder, ringer, ...","[Jack Black, Ana de la Reguera, Héctor Jiménez]","[{""credit_id"": ""52fe44ecc3a36847f80b2023"", ""de..."

## Extracting the director's name

In [16]:
def convert_dir(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            l.append(i['name'])
            break
    return l

In [17]:
movie['crew']=movie['crew'].apply(convert_dir)
movie

C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\3666180790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['crew']=movie['crew'].apply(convert_dir)

,id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]",Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
1494,10719,"[Comedy, Family, Fantasy]",Elf,When young Buddy falls into Santa's gift sack ...,"[holiday, elves, santa claus, looking for bir...","[Will Ferrell, James Caan, Zooey Deschanel]",[Jon Favreau]
1495,9294,"[Drama, Fantasy, Romance, Science Fiction]",Phenomenon,An ordinary man sees a bright light descend fr...,"[brain tumor, telekinesis, genius, terminal il...","[John Travolta, Kyra Sedgwick, Forest Whitaker]",[Jon Turteltaub]
1496,11888,"[Adventure, Comedy, Family]",Snow Dogs,When a Miami dentist inherits a team of sled d...,"[adoption, log cabin, alaska, sled dogs]","[Jim Belushi, Cuba Gooding Jr., James Coburn]",[Brian Levant]
1497,9647,"[Fantasy, Comedy, Drama]",Scrooged,"In this modern take on Charles Dickens' ""A Chr...","[holiday, tv ratings, comedy, scrooge, christm...","[Bill Murray, Karen Allen, John Forsythe]",[Richard Donner]
1498,9353,"[Comedy, Family]",Nacho Libre,Nacho Libre is loosely based on the story of F...,"[nun, sport, orphanage, ordensbruder, ringer, ...","[Jack Black, Ana de la Reguera, Héctor Jiménez]",[Jared Hess]

## converting overview column into list of string

In [18]:
movie['overview']=movie['overview'].apply(lambda x:x.split())
movie

C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\3304104870.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['overview']=movie['overview'].apply(lambda x:x.split())

,id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
1494,10719,"[Comedy, Family, Fantasy]",Elf,"[When, young, Buddy, falls, into, Santa's, gif...","[holiday, elves, santa claus, looking for bir...","[Will Ferrell, James Caan, Zooey Deschanel]",[Jon Favreau]
1495,9294,"[Drama, Fantasy, Romance, Science Fiction]",Phenomenon,"[An, ordinary, man, sees, a, bright, light, de...","[brain tumor, telekinesis, genius, terminal il...","[John Travolta, Kyra Sedgwick, Forest Whitaker]",[Jon Turteltaub]
1496,11888,"[Adventure, Comedy, Family]",Snow Dogs,"[When, a, Miami, dentist, inherits, a, team, o...","[adoption, log cabin, alaska, sled dogs]","[Jim Belushi, Cuba Gooding Jr., James Coburn]",[Brian Levant]
1497,9647,"[Fantasy, Comedy, Drama]",Scrooged,"[In, this, modern, take, on, Charles, Dickens'...","[holiday, tv ratings, comedy, scrooge, christm...","[Bill Murray, Karen Allen, John Forsythe]",[Richard Donner]
1498,9353,"[Comedy, Family]",Nacho Libre,"[Nacho, Libre, is, loosely, based, on, the, st...","[nun, sport, orphanage, ordensbruder, ringer, ...","[Jack Black, Ana de la Reguera, Héctor Jiménez]",[Jared Hess]

## Removing the spaces b/w the words for making it easy to search for a word

In [19]:
movie['genres']=movie['genres'].apply(lambda x: [i.replace(" ","") for i in x])
movie['keywords']=movie['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
movie['cast']=movie['cast'].apply(lambda x: [i.replace(" ","") for i in x])
movie['crew']=movie['crew'].apply(lambda x: [i.replace(" ","") for i in x])
movie

C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\3567161323.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['genres']=movie['genres'].apply(lambda x: [i.replace(" ","") for i in x])
C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\3567161323.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['keywords']=movie['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\3567161323.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['cast']=movie['cast'].apply(lambda x: [i.replace(" ","") for i in x])
C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\3567161323.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['crew']=movie['crew'].apply(lambda x: [i.replace(" ","") for i in x])

,id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,"[Action, Adventure, Crime]",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,"[Action, Adventure, ScienceFiction]",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...,...
1494,10719,"[Comedy, Family, Fantasy]",Elf,"[When, young, Buddy, falls, into, Santa's, gif...","[holiday, elves, santaclaus, lookingforbirthpa...","[WillFerrell, JamesCaan, ZooeyDeschanel]",[JonFavreau]
1495,9294,"[Drama, Fantasy, Romance, ScienceFiction]",Phenomenon,"[An, ordinary, man, sees, a, bright, light, de...","[braintumor, telekinesis, genius, terminalilln...","[JohnTravolta, KyraSedgwick, ForestWhitaker]",[JonTurteltaub]
1496,11888,"[Adventure, Comedy, Family]",Snow Dogs,"[When, a, Miami, dentist, inherits, a, team, o...","[adoption, logcabin, alaska, sleddogs]","[JimBelushi, CubaGoodingJr., JamesCoburn]",[BrianLevant]
1497,9647,"[Fantasy, Comedy, Drama]",Scrooged,"[In, this, modern, take, on, Charles, Dickens'...","[holiday, tvratings, comedy, scrooge, christma...","[BillMurray, KarenAllen, JohnForsythe]",[RichardDonner]
1498,9353,"[Comedy, Family]",Nacho Libre,"[Nacho, Libre, is, loosely, based, on, the, st...","[nun, sport, orphanage, ordensbruder, ringer, ...","[JackBlack, AnadelaReguera, HéctorJiménez]",[JaredHess]

## Combining many columns

In [20]:
movie['tag']=movie['overview']+movie['genres']+movie['keywords']+movie['cast']+movie['crew']

C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\275208242.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['tag']=movie['overview']+movie['genres']+movie['keywords']+movie['cast']+movie['crew']

## Making new dataFrame

In [21]:
new_movie=movie[['id','title','tag']]
new_movie

,id,title,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
1494,10719,Elf,"[When, young, Buddy, falls, into, Santa's, gif..."
1495,9294,Phenomenon,"[An, ordinary, man, sees, a, bright, light, de..."
1496,11888,Snow Dogs,"[When, a, Miami, dentist, inherits, a, team, o..."
1497,9647,Scrooged,"[In, this, modern, take, on, Charles, Dickens'..."
1498,9353,Nacho Libre,"[Nacho, Libre, is, loosely, based, on, the, st..."

## Combining all words in tag column

In [22]:
new_movie['tag']=new_movie['tag'].apply(lambda x:" ".join(x))
new_movie

C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\2812110445.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movie['tag']=new_movie['tag'].apply(lambda x:" ".join(x))

,id,title,tag
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
1494,10719,Elf,When young Buddy falls into Santa's gift sack ...
1495,9294,Phenomenon,An ordinary man sees a bright light descend fr...
1496,11888,Snow Dogs,When a Miami dentist inherits a team of sled d...
1497,9647,Scrooged,"In this modern take on Charles Dickens' ""A Chr..."
1498,9353,Nacho Libre,Nacho Libre is loosely based on the story of F...

## Stemming

In [23]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [24]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return y

In [25]:
new_movie['tag'].apply(stem)

0       [in, the, 22nd, century,, a, parapleg, marin, ...
1       [captain, barbossa,, long, believ, to, be, dea...
2       [a, cryptic, messag, from, bond’, past, send, ...
3       [follow, the, death, of, district, attorney, h...
4       [john, carter, is, a, war-weary,, former, mili...
                              ...
1494    [when, young, buddi, fall, into, santa', gift,...
1495    [an, ordinari, man, see, a, bright, light, des...
1496    [when, a, miami, dentist, inherit, a, team, of...
1497    [in, thi, modern, take, on, charl, dickens', "...
1498    [nacho, libr, is, loos, base, on, the, stori, ...
Name: tag, Length: 1499, dtype: object

## Converting every letter to lower case

In [26]:
new_movie['tag']=new_movie['tag'].apply(lambda x:x.lower())
new_movie

C:\Users\MY DELL\AppData\Local\Temp\ipykernel_21432\741868826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movie['tag']=new_movie['tag'].apply(lambda x:x.lower())

,id,title,tag
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
1494,10719,Elf,when young buddy falls into santa's gift sack ...
1495,9294,Phenomenon,an ordinary man sees a bright light descend fr...
1496,11888,Snow Dogs,when a miami dentist inherits a team of sled d...
1497,9647,Scrooged,"in this modern take on charles dickens' ""a chr..."
1498,9353,Nacho Libre,nacho libre is loosely based on the story of f...

In [27]:
new_movie.iloc[0]

id                                                   19995
title                                               Avatar
tag      in the 22nd century, a paraplegic marine is di...
Name: 0, dtype: object

# Vectorization of Words

-> Find the freq. of all the words occurs in whole tag columns
-> Then we can extract the no. of required words for prediction

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english') # we need 5000 freq. for prediction and we r removing the stop words of english lang.

In [29]:
vector=cv.fit_transform(new_movie['tag']).toarray()
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zoo', 'zooeydeschanel', 'zookeeper'],
      dtype=object)

## Distance calculation of 1 movie to another - using Cosine distance(calculation angle b/w 2 movies)

##### Eucledian distance give incorrect o/p for large values

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

In [32]:
similarity=cosine_similarity(vector)

In [33]:
similarity[0]

array([1.        , 0.0805823 , 0.05372153, ..., 0.03539962, 0.02139802,
       0.        ])

## using enumerate for pairing index with similarity values

#### Reverse sorting on based on the values

In [34]:
sorted(enumerate(similarity[0]),reverse=True,key=lambda x:x[1])[1:6]

[(539, 0.23816525581123338),
 (507, 0.23314714686961358),
 (1191, 0.22522130823072545),
 (1213, 0.22400716834408235),
 (1201, 0.21957751641342)]

In [35]:
def recommend(movie_name):
    movie_index=new_movie[new_movie['title']==movie_name].index[0]
    l=sorted(enumerate(similarity[movie_index]),reverse=True,key=lambda x:x[1])[1:6]
    for i in l:
        print(new_movie.iloc[i[0]].title)

In [36]:
recommend('Avatar')

Titan A.E.
Independence Day
Small Soldiers
Aliens vs Predator: Requiem
Predators

In [37]:
# pk.dump(new_movie,open('movie.pkl','wb'))

In [38]:
# pk.dump(similarity,open('similarity.pkl','wb'))